# Generated by Django 5.0.3 on 2024-04-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0003_alter_comment_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_groups",
            field=models.ManyToManyField(
                through="social_media.UserGroupChat", to="social_media.chatgroup"
            ),
        ),
    ]
