# Generated by Django 5.0.3 on 2024-04-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0006_postmedia_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postmedia",
            name="media_type",
        ),
        migrations.AddField(
            model_name="post",
            name="media_type",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
