# Generated by Django 5.0.3 on 2024-05-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0012_alter_chatgroup_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="replycomment",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
