# Generated by Django 5.0.3 on 2024-05-16 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0014_rename_user_notification_post_notification_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="social_media.post"
            ),
        ),
    ]
