# Generated by Django 5.0.3 on 2024-05-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0015_alter_notification_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="seen",
            field=models.BooleanField(default=False),
        ),
    ]
