# Generated by Django 5.0.3 on 2024-04-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0005_alter_message_options_userfollowing_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmedia",
            name="order",
            field=models.SmallIntegerField(default=1),
        ),
    ]
