# Generated by Django 5.0.3 on 2024-04-29 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0007_remove_postmedia_media_type_post_media_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postmedia",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="postmedia",
            unique_together={("order", "post")},
        ),
    ]
