# Generated by Django 5.0.3 on 2024-04-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0009_alter_postmedia_media_url_alter_postmedia_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media_type",
            field=models.CharField(default="Images", max_length=100),
        ),
    ]
