# Generated by Django 5.0.3 on 2024-05-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0011_alter_postmedia_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatgroup",
            name="name",
            field=models.CharField(default="Duo", max_length=100),
        ),
    ]
